# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python3 -V  # Print out python version for debugging
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install -U pip


build_wheel:
  stage: build
  script:
    - pip3 install wheel
    - sed 's/^python-Levenshtein==0.12.0/python-Levenshtein-wheels==0.13.2/' requirements.txt > requirements.txt # Remplace python-Levenshtein-wheels
    - sed 's/^sphinxcontrib-openapi=/#sphinxcontrib-openapi=/' requirements.txt > requirements.txt
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 week
  tags:
    - python-dinp-tscapx004r


upload_wheel:
  stage: deploy
  script:
    - pip3 install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/
  tags:
    - python-dinp-tscapx004r
  when: manual


staging:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf ${INSTALL_DIR}
    - mkdir -p ${INSTALL_DIR}
    - python3 -m venv ${INSTALL_DIR}
    - source ${INSTALL_DIR}/bin/activate
    - pip3 install -U pip
    - pip3 install --find-links=dist/ ${CI_PROJECT_NAME}
    - 'curl --insecure --header "JOB-TOKEN: ${CI_JOB_TOKEN}" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/sivnorm_referentiel/${MODEL_VERSION}/sivnorm_referentiel.tar'
    - tar xvf sivnorm_referentiel.tar 
    - cp -R sivnorm_referentiel /home/integ/
  tags:
    - python-dinp-tscapx004r


