version: '2.3'
services:
   sivnorme:
    container_name: ${USER}-sivnorme
    build: 
      context: ./docker/flask-api
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    env_file:
      - docker/env.list
    environment:
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
    ports:
     - "5557:5000"
    volumes:
     - /home/dss:/dss
    command: "python app/app.py"
