version: '2.3'
services:
   sivnorme:
    image: ${PROJECT_NAME}-${APP}:${APP_VERSION}
    container_name: ${PROJECT_NAME}-${APP}
    build:
      context: .
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        APP_PORT: ${APP_PORT}
        APP_PATH: /${APP}
    environment:
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
     - BASE_MODEL_PATH=${BASE_MODEL_PATH}
     - APP_PORT=${APP_PORT}
    ports:
    - ${APP_PORT}:${APP_PORT}
    networks:
     - isolated_nw

networks:
  isolated_nw:
    external:
     name: isolated_nw
