version: '2.3'
services:
   sivnorme:
    container_name: ${USER}-sivnorme
    build:
      context: ./docker/flask-api
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    env_file:
      - docker/env.list
    environment:
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
    ports:
     - ${APP_PORT}:5000
    networks:
     - isolated_nw
    volumes:
     - ${DSS_PATH}:/dss
     - ./:/app
    labels:
      - traefik.enable=true
      - traefik.backend=sivnorm
      - traefik.port=5000
      - traefik.frontend.rule=PathPrefix:/sivnorm,/swaggerui
    command: "python sivnorm/app.py"

networks:
  isolated_nw:
    external:
     name: isolated_nw
