version: '2.3'
services:
   sivnorme:
    image: ${PROJECT_NAME}-sivnorm-${EXEC_ENV}:${APP_VERSION}
    container_name: ${PROJECT_NAME}-sivnorm-${EXEC_ENV}
    build:
      context: .
      target: ${EXEC_ENV}
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    environment:
     - http_proxy=${http_proxy}
     - https_proxy=${http_proxy}
     - no_proxy=${no_proxy}
     - BASE_MODEL_PATH=${BASE_MODEL_PATH}
    ports:
     - ${APP_PORT}:5000
    networks:
     - isolated_nw
    volumes:
      - ./:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.sivnorm.entrypoints=http
      - traefik.http.routers.sivnorm.rule=PathPrefix(`/sivnorm`) || PathPrefix(`/swaggerui`)
      - traefik.http.services.sivnorm.loadbalancer.server.port=5000
    command: "python sivnorm/app.py"

networks:
  isolated_nw:
    external:
     name: isolated_nw
